sudo: false
language: python
install: pip install tox
matrix:
  include:
  - python: "2.7"
    env: TOX_ENV=py27
  - python: "3.8"
    env: TOX_ENV=static
  - python: "3.8"
    env: TOX_ENV=cov-travis DEPLOY=1
  - python: "3.8"
    env: TOX_ENV=docs
script: tox -e $TOX_ENV
after_success:
- test $TOX_ENV = docs && scripts/push-docs

deploy:
  provider: pypi
  user: __token__
  password:
    secure: "YaDQ27U3tXZXUMBHEvynfn6Rsssp5Vk/v9ZsRJHKv01jCrM8RPn1/92HD/u2s+bepsKsZ4xhD7nXBCmPghe6Mtybej7CRmLT21bOJeGeilH6s7wvK36mCSZ1HfUeQ6CB+v1AqRNoRxKr+oNMtgm+ryQw/VvJOWvwdawBM9rjaeJ5EjMXMcA92E334xH/gMCnKDebtNwR5kg5p0SkQrgdPThQGNlTL6ohrEHd4yI5cKijdGSGUUNXxd0/SKTeT8yHjAf3V9/XAzl8624DiAlqwnuwlPL6B9S8QsHwf2ju5DYCGNOYQnZ6a0nUUTb0mBdNYXsGL5jpy3/QsJZfcXAQiWpb67GwK9Po104EbrdzM6BZumIbJk+mKw2NAHtUczocMmr717wgFHq5uN90xJBxdCh6BHLrzeSRnk3j30XIkzuV8lk+9pfHL8+XU+10oziXYG913IywXA5IgC9J8q9I7mxYaEbx3RncVMf6JsWIr47sZaf61i2d66F9wZj1FGLQsMffXgfYfV1purv69b1o5AzHwtkasoM6VS6G0vJ7S9pU10YRwf3+CUkriqM4dv51ipcxPXNRpK8h/0F1kLeuNjEG0+zfviIXfUsURRzAHk2xfDU6WFE2Fk5HvNJqRXvXhuFpgSUxXAt5XB/u7CfQjueWUIl/Z63mAKrn4mjHg4c="
  on:
    tags: true
    condition: $DEPLOY = 1
  skip_existing: true
